name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create API directory
        run: mkdir -p api
      - name: Create API endpoint
        run: |
          cat > api/hello.js << EOL
          export default function handler(request, response) {
            response.status(200).json({ message: 'Hello, World!' })
          }
          EOL
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: \${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
